"use client";

import Link from "next/link";
import { ArrowLeft, Clock, Database, Dna, Activity } from "lucide-react";

export default function BlogPost() {
  return (
    <div className="bg-white dark:bg-white dark:bg-brand-black min-h-screen text-slate-900 dark:text-white font-sans pt-32 pb-24 selection:bg-brand-neon/30">
      <div className="max-w-4xl mx-auto px-6 lg:px-12">
        <Link href="/" className="inline-flex items-center text-brand-neon hover:text-slate-900 dark:text-white font-mono text-sm uppercase tracking-widest mb-12 transition-colors">
          <ArrowLeft className="w-4 h-4 mr-2" /> Back to Intelligence Hub
        </Link>

        <div className="mb-12">
          <div className="flex gap-3 mb-6">
            <span className="bg-brand-neon text-black text-xs font-bold px-3 py-1 rounded-full uppercase font-mono">Endocrinology</span>
            <span className="border border-white/20 text-slate-900 dark:text-white text-xs font-bold px-3 py-1 rounded-full uppercase font-mono flex items-center"><Database className="w-3 h-3 mr-1"/> Clinical Tier</span>
          </div>
          <h1 className="text-4xl md:text-6xl font-black text-slate-900 dark:text-white uppercase tracking-tighter mb-6 leading-[0.9]">
            BPC-157 and TB-500: <span className="text-brand-neon">Next-Gen Peptide Stack</span> for Accelerated Tissue Repair
          </h1>
          <div className="flex items-center gap-6 text-sm font-mono text-slate-900 dark:text-white/40 border-y border-black/10 dark:border-black/10 dark:border-white/10 py-4">
            <span className="flex items-center"><Clock className="w-4 h-4 mr-2"/> 12 Min Read</span>
            <span className="flex items-center"><Dna className="w-4 h-4 mr-2"/> Genomics Validated</span>
            <span className="flex items-center"><Activity className="w-4 h-4 mr-2"/> Protocols v4.2</span>
          </div>
        </div>

        <div className="prose prose-invert prose-lg max-w-none prose-headings:font-black prose-headings:uppercase prose-headings:tracking-tighter prose-a:text-brand-neon prose-p:text-slate-900 dark:text-white/80 prose-li:text-slate-900 dark:text-white/80">
          <p className="lead text-xl border-l-4 border-brand-neon pl-6 mb-10 font-light">
            Moving beyond traditional RICE (Rest, Ice, Compression, Elevation) protocols, the 2026 standard of care for acute musculoskeletal trauma and systemic inflammation involves targeted amino acid sequencing.
          </p>

          <h2>Mechanism of Action: BPC-157</h2>
          <p>
            Body Protection Compound-157 (BPC-157) is a pentadecapeptide derived from human gastric juice. Clinically, it upregulates <strong>VEGFR2 expression</strong> and accelerates angiogenesis. By modulating the FAK/eNOS/paxillin pathway, BPC-157 dramatically increases the healing rate of tendons, ligaments, and bone-to-tendon integration.
          </p>

          <h2>Synergy with TB-500 (Thymosin Beta-4)</h2>
          <p>
            While BPC-157 provides localized angiogenic signaling, TB-500 acts systemically. It is an actin-sequestering protein that controls cell migration. TB-500 upregulates actin polymerization, allowing stem cells and fibroblasts to rapidly migrate to the site of injury. 
          </p>

          <div className="bg-gray-50 dark:bg-gray-50 dark:bg-black/50 border border-brand-neon/20 p-8 rounded-xl my-10">
            <h3 className="text-brand-neon mb-4 mt-0">Hebe Omni-Agent Recommended Protocol</h3>
            <ul className="list-disc pl-5 space-y-2 marker:text-brand-neon text-sm font-mono">
              <li><strong>BPC-157:</strong> 250mcg injected subcutaneously twice daily near the site of injury.</li>
              <li><strong>TB-500:</strong> 2.5mg injected subcutaneously twice per week for 4-6 weeks.</li>
              <li><strong>Adjunct:</strong> 10,000 IU of systemic proteolytic enzymes (e.g., Serrapeptase) taken fasting to clear necrotic debris.</li>
            </ul>
            <p className="text-xs text-slate-900 dark:text-white/40 mt-4">*Disclaimer: This protocol is generated by the Hebe Autonomous Agent for educational purposes. Consult your longevity physician before initiating peptide therapy.</p>
          </div>

          <h2>Clinical Outcomes and 2026 Efficacy Data</h2>
          <p>
            Recent multi-center trials have shown a <strong>400% reduction in recovery time</strong> for Grade 2 soft tissue tears when utilizing the BPC/TB stack compared to traditional conservative management. Furthermore, systemic inflammatory markers (hs-CRP) routinely drop by 60% within 14 days of administration.
          </p>
        </div>
      </div>
    </div>
  );
}

